### ISSUE TITLE
What about Timeline animation?

### ISSUE THREAD

**Issue by maximusnikulin** [hyperfuse/react-anime#16]
Hi there. Could you give some example to animate components one by one, like kind of **TimeLine** animation in anime.js. It's not staggerAnimation of list's items. I want to animate two different components in two different places of page, but one by one. I know how it may be implemented with anime.js or gsap.
Is there some way to make it with react-anime?.
http://anime-js.com/documentation/#basicTimeline
I'll be grateful for any help, thanks.

**Comment by alaingalvan** [comment]
Controlling multiple components in different components would require the 2 components to share state in some way. Let me try cooking up an example here:

Lets say for instance, we have a *view* with `Header` and `Body` components. 

We want it so that if we click a button, a unique animation will play one each of these components, 1 by 1.

```js
import { Component } from 'react';

 class View extends Component {

  triggerAnimation = () => {
    // Stub
  }

 render() {
    return (
      <div>
        <Header/>
        <Body/>
        <Button onClick={this.tiggerAnimation}/>
      </div>
    );
  }
}
```

## Workaround - Delay

One way to go about doing this is to set the delay of each element to be whatever the duration would be in timeline, for instance, I do that in the intro animation of the [React Anime Github Page](https://github.com/hyperfuse/react-anime/blob/master/packages/react-anime-website/src/components/logo.js#L26).

The whole point of a Timeline is to centralize those keyframes in one place though...

## Future Work

Perhaps some future work should be defining a `<Timeline/>` element:

```js
let Logo = () => (
  <Timeline>
    <Keyframe>
      <LogoOutline/>
    </Keyframe>
   <Keyframe>
      <LogoLines/>
    <Keyframe>
  </Timeline>
);
```

Sounds like a good feature for **2.1**!

**Comment by maximusnikulin** [comment]
Oh thanks a lot, I am looking forward Timeline component. I'll use workaround solution. Thanks for the help.

**Comment by tujoworker** [comment]
Actually, we can use a trick here!

```jsx
<Anime
    autoplay={false}
    ref={ref => {
        console.log('ref', ref);
        setTimeout(() => {
            ref.anime.play();
        }, 2e3);
        this._ref = ref;// this way we can control the animation also outside!
    }}
    ...
>
...
</Anime>
```

**Comment by dperolio** [comment]
Was this functionality ever added? :c
