### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by polmoneys** [hyperfuse/react-anime#9]
It would be lovely if there were moar examples on the readme, I can't seem to trigger another animation using the complete callback, like in https://github.com/juliangarnier/anime/blob/master/examples/callbacks.html

TIA

**Comment by kennetpostigo** [comment]
Hey @polmoneys you are definitely right! We have some examples that aren't linked in the docs just been busy since we're working on stuff for our research company. Here are the links to the other examples:
- http://codepen.io/alaingalvan/pen/rrZXYB
- http://codepen.io/alaingalvan/pen/RGWbmp

Are these helpful?

**Comment by polmoneys** [comment]
Fantastic, gracias !

**Comment by abattenburg** [comment]
I'm also having trouble triggering the complete callback. Looking at the documentation, I've tried passing a second previously declared  <Anime > function in as a parameter, and declaring a new one inside the function. Neither seems to have any effect. Thanks for the help, I know I'm missing something obvious here...

**Comment by alaingalvan** [comment]
@abattenburg I made a quick [pen](http://codepen.io/alaingalvan/pen/rWVNpd?editors=0010) that uses the complete callback, and it seems to be working, have you tried updating your version of React Anime?
